apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-app.fullname" . }}  # Use the chart name
spec:
  type: {{ .Values.service.type }}  # Parameterize service type
  selector:
    app: {{ include "hello-app.name" . }}  # Use chart name
  ports:
    - port: {{ .Values.service.port }}  # Parameterize service port
      targetPort: {{ .Values.service.targetPort }}  # Parameterize target port
